// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqrilgotvgowovsovidu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxcmlsZ290dmdvd292c292aWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzA4NTUsImV4cCI6MjA2NzU0Njg1NX0.qasO7x3toos1LiZU8ffXrfQwhOvdKAgDbjvvNrD6uxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});